#!/bin/sh
set -e

# Use the absolute path to the nginx html folder try
CONFIG_FILE="/usr/share/nginx/html/config.js"

echo "Writing config to $CONFIG_FILE"

# Create the file with the values from Azure Env Vars
cat <<EOF > $CONFIG_FILE
window.appConfig = {
  VITE_PLANT_API_URL: "$VITE_PLANT_API_URL",
  VITE_AUTH_API_URL: "$VITE_AUTH_API_URL",
  VITE_AI_API_URL: "$VITE_AI_API_URL",
  DATADOG_RUM_ENABLED: "$DATADOG_RUM_ENABLED",
  DATADOG_RUM_APPLICATION_ID: "$DATADOG_RUM_APPLICATION_ID",
  DATADOG_RUM_CLIENT_TOKEN: "$DATADOG_RUM_CLIENT_TOKEN",
  DATADOG_SITE: "$DATADOG_SITE",
  DATADOG_ENV: "$DATADOG_ENV",
  DATADOG_VERSION: "$DATADOG_VERSION",
  DATADOG_RUM_SERVICE: "$DATADOG_RUM_SERVICE",
  DATADOG_RUM_SESSION_SAMPLE_RATE: "$DATADOG_RUM_SESSION_SAMPLE_RATE",
  DATADOG_RUM_REPLAY_SAMPLE_RATE: "$DATADOG_RUM_REPLAY_SAMPLE_RATE",
  DATADOG_RUM_REPLAY_ENABLED: "$DATADOG_RUM_REPLAY_ENABLED"
};
EOF

echo "Content of $CONFIG_FILE:"
cat $CONFIG_FILE

# Start Nginx
exec "$@"
