apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vhg-app
  namespace: {{ .Release.Namespace }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: {{ .Values.path | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.destinationNamespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
