apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vhg-app
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: {{ .Values.path | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.destinationNamespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
