sonar.projectKey=virtual-herbal-garden
sonar.projectName=Virtual Herbal Garden
sonar.sourceEncoding=UTF-8
sonar.sources=client/src,server,infra,vhg-chart
sonar.python.version=3.10
sonar.exclusions=client/dist/**,client/node_modules/**,server/**/__pycache__/**,server/**/*.pyc,server/build_**/**,**/*.lock,**/*.tfstate,**/*.tfstate.backup,**/*.tfvars,**/secrets.tfvars,**/secrets.tfvars.example,K8s/outputs.tf
