namespace: vhg-1
frontend:
  image: dharshan3690/navi-frontend
  tag: "1840"
  port: 80
plant:
  image: dharshan3690/plant-service
  tag: "1846"
  port: 8005
auth:
  image: dharshan3690/auth-service
  tag: "1846"
  port: 8006
ai:
  image: dharshan3690/ai-service
  tag: "1846"
  port: 8007
ingress:
  enabled: true
  className: nginx
# ... keep your existing configurations ...
rum:
  appId: "00e9c62c-5245-4154-bba7-ac9fc0af256d"
  clientToken: "pub143fff5a3e12cc5661044443cd7ba787"
  site: "us5.datadoghq.com"
otel:
  collectorHost: "datadog-otel-opentelemetry-collector.datadog.svc.cluster.local"
  collectorPort: "4318"
  env: "production"
