namespace: vhg-1
frontend:
  image: dharshan3690/navi-frontend
  tag: "1860"
  port: 80
  rum:
    enabled: true
    applicationId: "6e70653f-5b87-4945-a9e8-3e5da4e5e583"
    clientToken: "pubb693ad8f16f0580f6e609113ed67c985"
    service: "vhg-frontend"
    sessionSampleRate: "100"
    replaySampleRate: "0"
    replayEnabled: true
plant:
  image: dharshan3690/plant-service
  tag: "1859"
  port: 8005
auth:
  image: dharshan3690/auth-service
  tag: "1859"
  port: 8006
ai:
  image: dharshan3690/ai-service
  tag: "1859"
  port: 8007
ingress:
  enabled: true
  className: nginx
observability:
  enabled: true
  otlpEndpoint: "http://$(HOST_IP):4317"
  environment: "aks"
  datadogSite: "us5.datadoghq.com"
  serviceNamespace: "virtual-herbal-garden"
  tracesSampler: "parentbased_traceidratio"
  tracesSamplerArg: "1.0"
  metricExportInterval: "30000"
  excludedUrls: "/docs,/openapi.json"
