namespace: vhg-1

frontend:
  image: dharshan3690/navi-frontend
  tag: latest
  port: 80

plant:
  image: dharshan3690/plant-service
  tag: latest
  port: 8005

auth:
  image: dharshan3690/auth-service
  tag: latest
  port: 8006

ai:
  image: dharshan3690/ai-service
  tag: latest
  port: 8007

ingress:
  enabled: true
  className: nginx