apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: plant-service
  template:
    metadata:
      labels:
        app: plant-service
    spec:
      containers:
      - name: plant-service
        image: "{{ .Values.plant.image }}:{{ .Values.plant.tag }}"
        ports:
        - containerPort: 8005
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://{{ .Values.otel.collectorHost }}:{{ .Values.otel.collectorPort }}"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage,b3,datadog"
        - name: OTEL_SERVICE_NAME
          value: "plant-service"
        - name: OTEL_ENV
          value: "{{ .Values.otel.env }}"
        - name: DD_ENV
          value: "{{ .Values.otel.env }}"
        - name: DD_SERVICE
          value: "plant-service"
        - name: DD_VERSION
          value: "{{ .Values.plant.tag }}"
        envFrom:
        - secretRef:
            name: vhg-secrets
        livenessProbe:
          httpGet:
            path: /
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "256Mi"
            cpu: "150m"