apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: "{{ .Values.auth.image }}:{{ .Values.auth.tag }}"
        ports:
        - containerPort: 8006

        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://{{ .Values.otel.collectorHost }}:{{ .Values.otel.collectorPort }}"
        - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
          value: "grpc"
        - name: OTEL_SERVICE_NAME
          value: "auth-service"
        - name: OTEL_ENV
          value: "{{ .Values.otel.env }}"
        - name: DD_ENV
          value: "{{ .Values.otel.env }}"
        - name: DD_SERVICE
          value: "auth-service"
        envFrom:
        - secretRef:
            name: vhg-secrets

        livenessProbe:
          httpGet:
            path: /docs
            port: 8006
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /docs
            port: 8006
          initialDelaySeconds: 10
          periodSeconds: 5

        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "256Mi"
            cpu: "150m"