apiVersion: v1
kind: Secret
metadata:
  name: vhg-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_NhUByevj4lH5@ep-wild-bread-ahufw93p-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
  SECRET_KEY: "finiteloop_secret_secure_key_123"
  ALGORITHM: "HS256"
  PYTHON_VERSION: "3.10.13"

  CORS_ORIGINS: "*"

  POSTGRES_DB: "neondb"
  POSTGRES_HOST: "ep-wild-bread-ahufw93p-pooler.c-3.us-east-1.aws.neon.tech"
  POSTGRES_PASSWORD: "npg_NhUByevj4lH5"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "neondb_owner"

  MAIL_FROM: "dharshan122001@gmail.com"
  MAIL_PASSWORD: "nxwgqsnu jhfk khof"
  MAIL_PORT: "587"
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_SSL_TLS: "False"
  MAIL_STARTTLS: "True"
  MAIL_USERNAME: "dharshan122001@gmail.com"

  GEMINI_API_KEY: "AIzaSyDU2IRX8vjA5dtEfcuJ6IRAKuv4Ij1CBL4"
  GROQ_API_KEY: "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"
  PLANTNET_API_KEY: "2b10axG37F0YebW32fCdNG7Q"

  GMAIL_CLIENT_ID: "491680937929-m88h1v3rkremor2v6025aes8l2egqufd.apps.googleusercontent.com"
  GMAIL_CLIENT_SECRET: "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"
  GMAIL_REFRESH_TOKEN: "1//0gNUjID8oBv9JCgYIARAAGBASNwF-L9IrkeSzw_VBE71GWQIe4JP-lOM0FYZvbSQAWSfOCPt_Fn4_JCaBvAuCfKBKb-sMagwih8k"